package psd.api;

public enum CommandType {
    READ_RESOURCE,
    WRITE_RESOURCE,
    ASSIGN_PERMISSION,
    CREATE_RESOURCE,
    CREATE_ROLE,
    CREATE_USER,
    CHANGE_RIGHTS,
    CREATE_PERMISSION,
    ADD_PERMISSION_TO_ROLE, ASSIGN_ROLE
}
