create table USER_ROLE (
  USERNAME varchar(100) not null,
  ROLE_NAME varchar(100) not null,
  primary key (USERNAME, ROLE_NAME),
  FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME) ON DELETE CASCADE,
  FOREIGN KEY (ROLE_NAME) REFERENCES ROLE(ROLE_NAME) ON DELETE CASCADE
);